# Prework Assignment

### General Background Questions

1. Why is version control important in science?

It increases trust and credibility of the project within the scientific community. It also allows multiple developers or scientists to collaborate and work on the same project. It also creates backups so that progress of previous working branches would not be lost.

2. What kind of research artifacts can we track with Git?

Datasets, statistical code, figures, lab notes, and manuscript.

3. What are the three main things that can go wrong in a data science project?

1. Asking the wrong question
2. Choosing the wrong visualization tool
3. Skipping the analysis

### Python Background Questions

These short exercises are a way to familiarize yourself with python. If you find these exercises too difficult, don’t worry! We will review the basics the first day to make sure we are all comfortable coding in Python.

Please save your work in this document and `git push` them to the `prework-assignment` repo.

----------------------------------------------------------------

### Problem 1: Basic Operations

You are at Vanessa's Vegan Cafe and you loved it so much you wanna leave a tip. Write a function that takes the amount owed and calculates how much money you pay with an 18% tip. If functions still scare you, just the solution code will do.

In [2]:
def tips(amountOwed):
    return amountOwed*1.18

tips(200)

236.0

----------------------------------------------------------------

### Problem 2: Lists

I have a fortune cookie that says my lucky numbers are:

       [23, 54, 6, 8, 10078, 3]

Write a function that returns 3 lists (if functions still scare you, just the solution code will do)
   - replace the number 6 with 1
   - the above list in decreasing order
   - all values greater than 15

In [18]:
cookie = [23,54,6,8,10078,3]

def foo(bar):
    list1 = bar[:]
    list3 = bar[:]
    list1[2] = 1
    list2 = sorted(bar, reverse=True)
    list3 = [i for i in list3 if i > 15]
    return(list1,list2,list3)

foo(cookie)

([23, 54, 1, 8, 10078, 3], [10078, 54, 23, 8, 6, 3], [23, 54, 10078])

----------------------------------------------------------------

### Problem 3: Basic Operations

Let's now take the first step in coding some real data science. Write a statement that loads the `numpy` library into the interpreter and gives it an alias of `np`.

In [19]:
import numpy as np

----------------------------------------------------------------

### Problem 4: Numpy

Generated a 10x10 `numpy` array with random numbers and slice the array to get the 2nd and 3rd column. Also calculate the average of 6th column using `numpy`.

In [29]:
arr = np.random.randint(10, size=(10,10))
print(arr)
arr = arr[:10, 1:3]
print(arr)
avg = arr[:,6]

[[7 2 7 4 8 2 2 9 5 9]
 [7 2 5 7 0 9 2 1 6 6]
 [6 5 1 0 7 2 6 0 0 5]
 [5 7 6 4 9 6 6 3 1 9]
 [9 7 5 9 5 3 1 0 5 2]
 [9 8 3 6 1 7 1 4 4 9]
 [3 0 8 2 2 5 3 1 8 8]
 [7 8 5 6 6 5 9 2 3 5]
 [3 1 6 3 8 4 3 0 4 7]
 [2 6 6 4 7 8 7 8 3 4]]
[[2 7]
 [2 5]
 [5 1]
 [7 6]
 [7 5]
 [8 3]
 [0 8]
 [8 5]
 [1 6]
 [6 6]]


----------------------------------------------------------------

##### That's it! We look forward to seeing you in class!